### ISSUE TITLE
nosetests --with-tap not producing TAP

### ISSUE THREAD

**Issue by bluefeet** [mblayman/tappy#12]
Hello,

I'm a Perl developer looking to integrate some Selenium python tests with our build platform.  I installed tap.py and added --with-tap to my nosetests command and the output didn't change at all.  Any ideas how I can go about troubleshooting this?  I know that before I installed tap.py I'd get a failure immediately, but once installed nosetests ran, so the plugin is there, it just doesn't seem to be doing anything.  I haven't a clue.

Thanks!

**Comment by bluefeet** [comment]
Versions I have installed:

```
tap.py==1.4
nose==1.3.6
```

Command I run:

```
nosetests --with-tap path/to/tests
```

**Comment by mblayman** [comment]
@bluefeet, thanks for the report. When your run `nosetests path/to/tests`, do you get some standard Python test runner output (something like what is below)?
```bash
$ nosetests path/to/tests
...............
----------------------------------------------------------------------
Ran 15 tests in 0.020s

OK
```

If that's working, then running with `--with-tap` should create files with `.tap` extension in the same directory as where you ran `nosetests`.

Can you confirm that running without `--with-tap` is working? If it is working, then it sounds like you've run into a legitimate bug in tappy and we can try to debug more.

**Comment by bluefeet** [comment]
Oh!  I had missed the fact that a .tap file is create.  Hmm, now to figure out how to feed that into my build system - all my other tap-producers output tap on STDIN/OUT.  Thanks for responding!

**Comment by mblayman** [comment]
Glad I could help.

I originally designed tappy with CI systems in mind (like the Jenkins TAP plugin) so I defaulted to using files. Also, I didn't want to override the default behavior of the Python test runners.

I think streaming TAP and suppressing the default runner output would be a great feature. I'm going to close out this issue (because this reads more like a support ticket) and open another one to track a streaming feature.

Thanks for the input!

**Comment by bluefeet** [comment]
Thanks for the quick response!
