### ISSUE TITLE
Support subtests, rather than multiple files, in nosetest plugin

### ISSUE THREAD

**Issue by bluefeet** [mblayman/tappy#14]
For my particular use case it would be much better for me to have a single .tap file that combined the multiple files into a single tap output using subtests.

```
    # tests for Foo
    ok 1 - one
    ok 2 - two
ok 1 - Foo
    # tests for Bar
    ok 1 - one
    ok 2 - two
ok 2 - Bar
```

**Comment by mblayman** [comment]
@bluefeet Thanks for the suggestion. tappy adheres to the TAP specification and there is currently no support for subtests in the spec (see http://testanything.org/tap-specification.html if you're interested). A debate rages on with the TAP spec community on how to implement such a feature in a backwards compatible. I've read the threads and they are almost a flamewar so I'm not hopeful for consensus soon.

In the mean time, I just merged a `--tap-combined` option for the plugin that will combine all test cases into one file called `testresults.tap`. I'll be pushing out a release tonight for this new version of tappy.

I'm going to close out this issue because subtests are outside of my sphere of influence (since tappy will stick to the spec). I hope the combined option gets you most of what you need.
