### ISSUE TITLE
Consider making TAP file generation opt-in for the pytest plugin

### ISSUE THREAD

**Issue by jchampio** [mblayman/tappy#34]
After installing tappy, bare runs of `py.test` spam my local directory with .tap files. The only use case I have is generation of TAP streams on stdout, so IMHO, this behavior is undesirable. I should have to explicitly pass an option to tappy to have it generate TAP output of any kind.

**Comment by mblayman** [comment]
I made a deliberate design decision to output to files by default.

A few of the reasons are:
* I did not want to overtake the default test runner output for any of the supported test runners. This is especially true for py.test because plugins are automatically activated whereas the other systems are opt-in (e.g., `--with-tap` for nose). I thought this would be disorienting for users.
* Streaming by default means that you would have to opt-out to see the default runner output. I'm not crazy about flag of that fashion (e.g., something like `--tap-no-stream`).
* This aligns with what I envision is the biggest use case for tappy: CI servers. Most CI servers that I have ever configured have reporting plugins that expected to find output in specific files.

I think this `pytest.ini` configuration could address your problem. If that doesn't work, then there is definitely a settings bug here that should be fixed.
```ini
[pytest]
addopts = --tap-stream
```
I'm sorry your use case doesn't line up exactly with the design. I hope this suggestion helps. If it does, I'll close the issue. If it doesn't, we can use this issue to track that fact that setting `tap-stream` in `addopts` should provide the desired results.

**Comment by jchampio** [comment]
I agree with each of your three points, actually, and I'm currently using `addopts` as a work-around. But I'm advocating for a third option: do nothing by default. Installing the tappy plugin for pytest should give me options -- output to separate TAP files, to combined, to a stream, etc. -- but it shouldn't actually be activated unless I want explicitly want it to be.

As an example, the [pytest-twisted plugin](https://pypi.python.org/pypi/pytest-twisted) gives me the `--twisted` command line option _and_ a `twisted` INI token. But it doesn't enable the Twisted reactor by default. The plugin just gives me the option to do so. I think this approach still addresses your main points: you still don't override the standard by default, you don't need a "disable" flag, and CI servers could just add a `pytest.ini` token that you provide in order to get their TAP file output.

**Comment by mblayman** [comment]
That sounds like a pretty good approach. I thought it was a bit odd that pytest plugins appear to be activated *and run* by default (vs. the opt-in style in nose). So, may I pick your brain on a style? Installing tappy will create an active plugin, what do you think of these?
```console
$ py.test --tap-stream  # Stream to STDOUT
$ py.test --tap-files # Dump files to *.tap
$ py.test # Though active, tappy does nothing.
```
along with all the other options that the pytest plugin normally supports. Does that sound workable?

**Comment by jchampio** [comment]
+1
I really like that approach.

**Comment by jchampio** [comment]
Awesome, thanks for the quick turnaround!
