### ISSUE TITLE
TAPTestRunner not observing unittest.main() buffer keyword

### ISSUE THREAD

**Issue by Mark-E-Hamilton** [mblayman/tappy#40]
The TAPTestRunner does not buffer output when the buffer=True keyword is passed to unittest.main(). I have this simple test:

```
#!/usr/bin/env python
from __future__ import print_function
import sys
import unittest
import tap

class TestStuff(unittest.TestCase):

    def test(self):
        print("Some output")
        self.assertTrue(True)

if __name__ == '__main__':

    # A:
    unittest.main(exit=False)

    # B:
    unittest.main(buffer=True, exit=False)

    # C:
    runner = tap.TAPTestRunner()
    unittest.main(testRunner=runner, exit=False)

    # D:
    runner = tap.TAPTestRunner()
    unittest.main(buffer=True, testRunner=runner, exit=False)

```

Case A and case B both produce the output I expect: the message printed by the test is displayed at A, and not displayed at B:

```
# A Output
Some output
.
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK

```
```
# B Output
.
----------------------------------------------------------------------
Ran 1 test in 0.000
OK
```
However,  the C and D cases both display the output from the test; IMO the D case should not.

```
Some output
.
----------------------------------------------------------------------
Ran 1 test in 0.002s
OK

```

**Comment by mblayman** [comment]
Mark, thanks for the report! tappy supports back to Python 2.6 where the buffer feature did not exist. I suspect that the reason this is failing is because the `__init__` for the `TestResult` class does not accept additional parameters in 2.6. In 2.7, it added some keyword arguments.

I'll try fiddling with the `__init__` and conditionally calling `super` methods with different call signatures based on version. I hope that will solve the issue.

**Comment by mblayman** [comment]
I took a closer look and realized there is not a bug here. The "bug" is in the test script. The problem is that the `buffer` parameter was not given to the runner constructor. When the runner is not explicitly passed into `unittest.main`, `main` will construct its own runner and pass in the `buffer` parameter. When the runner is provided, the `buffer` parameter is not used. In order to use `buffer` with an explicit runner (as is the case with `TAPTestRunner`), `buffer` must be provided to the runner. When I passed `buffer=True` to the runner, the test script worked as you would expect.

```python
# D:
runner = tap.TAPTestRunner(buffer=True)
unittest.main(buffer=True, testRunner=runner, exit=False)
```

Note that this API wart is also true of the `TextTestRunner`. I tried:

```python
# E:
runner = unittest.TextTestRunner()
unittest.main(buffer=True, testRunner=runner, exit=False)
```

and it failed to suppress the output.

Thanks for helping me understand this better. It took some good source diving before this made sense.

**Comment by Mark-E-Hamilton** [comment]
Thanks for looking at this. The interesting thing is that we use a TAP 
implementation written in-house, and it doesn't exhibit the behavior you 
found. We invoke it this way:

   unittest.main(buffer=True, testRunner=TAP())

and the output is suppressed. Not sure what we did to fix this, but it's 
good to know where to look.

-- 
----------------
Mark E. Hamilton
Engineering Sciences Center
Senior Member of Technical Staff
Sandia National Laboratories
505-844-7666

**Comment by mblayman** [comment]
Oh, that's intriguing. If you find that there's a way to trigger an explicitly supplied runner to buffer by just setting in the `main` function, I'd love to hear it. That might be a worthwhile addition to the runner code.
