### ISSUE TITLE
Rework developer workflow

### ISSUE THREAD

**Issue by mblayman** [mblayman/tappy#42]
The current development workflow does not use pip. This is pretty lame because `python setup.py develop` takes no advantage of caching. Change the flow to make better use of pip.

**Comment by mblayman** [comment]
Document it way better.

**Comment by mblayman** [comment]
@Mark-E-Hamilton I cleaned up the contributing guidelines to explain how I would set up tappy for development. Do you mind taking a look to see what you think? It's the `Setup` section of the contributing page at http://tappy.readthedocs.org/en/latest/contributing.html.

Is that sufficient? Is more needed? less?

**Comment by Mark-E-Hamilton** [comment]
It doesn't look like the requirements-dev.txt file has been pushed yet, 
so it's not something I can test out. I don't know about other users, 
but I have rarely used pip, mostly because we don't want to install 
things directly into any of our python installations. (It also might 
have something to do with me being a little old-school.) However, pip 
does have a --target option to specify where to install things. Once the 
requirements file is present I can give it a try.

I'll have to look at virtualenv also, and its not something I'm familiar 
with.

-- 
----------------
Mark E. Hamilton
Engineering Sciences Center
Senior Member of Technical Staff
Sandia National Laboratories
505-844-7666

**Comment by mblayman** [comment]
The `requirements-dev.txt` file is on master. Perhaps your master is out of sync? If you've never used `virtualenv`, I think you're in for a treat. It's basically a directory where you can install stuff without worrying about affecting the system installed version of Python. As a bonus, no root access is required.

For example, if you install with an activated virtual environment, then the package files would go to `~/my-virtual-env/lib/python2.7/site-packages` rather than `/usr/lib/python2.7/site-packages`. The activated environment adds stuff to `PYTHONPATH` so it automatically "knows" to check those locations for additional packages.

As someone who works on many different Python projects, I would toast without `virtualenv`.

**Comment by Mark-E-Hamilton** [comment]
On 03/21/16 14:01, Matt Layman wrote:
> The |requirements-dev.txt| file is on master. Perhaps your master is out
> of sync?

Arrgh! I'm just not used to working with GitHub. I'm used to pulling 
directly from the main repository. IAE, I've got it now. I'll have a 
look at it when I get a chance. Thanks.

-- 
----------------
Mark E. Hamilton
Engineering Sciences Center
Senior Member of Technical Staff
Sandia National Laboratories
505-844-7666
