### ISSUE TITLE
Docs improvement: Explain plan model

### ISSUE THREAD

**Issue by rpkilby** [mblayman/tappy#51]
I primarily work in python, but some recent work in the node.js world introduced me to TAP. Specifically, node-tap, which has explicit plan counts. eg, 

```js
import tap from 'tap';

tap.test('some test description', function(t) {
    t.plan(2);
    t.ok(true);
});
```

In addition to the other benefits of TAP, the plan count is a great sanity check. In the above, the test case fails because it's expected that two assertions be made.

In tappy (and other python TAP implementations), there doesn't seem to be an explicit plan count check. However, it looks like tappy tries to infer some plan count, although it's not immediately clear how it works, what it does, or what the count is for. So, 
- could you explain how plan works in tappy? :)
- is the plan count the number of `TestCase`s, the number of `test_method`s, the the number of `self.assert()`s?
- would it make sense to add an explicit `self.plan()` method to `TestCase`?
- also, if plan is supposed to infer how many assertions *should* be made, the below is a false positive. I would expect a plan count of 1, but the assertion is never executed. 
```py
    def test_with_assert_raises(self):
        with self.assertRaises(Exception):
            raise Exception('')

            self.assertTrue(False)
```

**Comment by mblayman** [comment]
@rpkilby, great questions, thanks for asking. Whatever the outcome of this discussion, it sounds like the documentation needs to be beefed up on this topic. :smile: 

> could you explain how plan works in tappy? is the plan count the number of `TestCase`s, the number of `test_method`s, the the number of `self.assert()`s?

The plan is purely generated from the count of test *methods* that are within the suite. The plan is there to comply with the TAP spec.

I made the design decision to base TAP lines on test methods because that is the default expectation within the Python ecosystem. `unittest`, `nose`, `pytest`, `trial`, etc. all report their results (i.e. `.`, `F`, `E`) at the method level. Per assertion could be pretty cool, but I didn't want to diverge from that expectation.

As you may know, TAP originates from Perl's ecosystem. In Perl's `Test::More`, the plan could either be a number or a special `noplan` string. Given those options, that led to a few mental models for thinking about the plan. Conceptually, plans can:

* be at the top of the stream and be like "there *should be* this many tests"
* be at the bottom of the stream and be like "there *should have been* this many tests"
* be at the bottom of the stream and be like "there *were* this many tests"

Of those modes, tappy adopts the last one. The reason for that choice is because of how Python test runners work. In a Python test run, each test method runs, regardless of whether previous tests failed or erred. Since tappy reports at the test method level and runners will run all tests, the plan should always match the count. If there is a mismatch, it would indicate a broken *runner* and not a broken test suite.

Let's quickly contrast this with `Test::More`. In a `Test::More` test run, the test runs as a top to bottom script. Any error (i.e., `E` in Python-land) causes the entire test script to "crash" and the rest of the tests do not run. It's hopefully clear how the plan becomes super valuable in that environment.

> would it make sense to add an explicit `self.plan()` method to `TestCase`?

Typing all this out is leading me to a conclusion that supporting a `plan()` method would not make much sense to me. If test runners guarantee to run all tests even if there's an error, what would an explicit plan buy a developer? If I'm missing some use case here, I'm all ears.

> also, if plan is supposed to infer how many assertions should be made, the below is a false positive. I would expect a plan count of 1, but the assertion is never executed.

Because plans are method based, the example is not a false positive. Hurray!

I hope this is a satisfactory answer. Let me know if you have questions. I'll leave the issue open as a reminder to make the plan documentation better. Thanks!

**Comment by rpkilby** [comment]
Hi @mblayman - thanks for the in-depth answer. I looked into the possibility of an assertion based plan mechanism, but agree that it's not really feasible. Each assert method would have to increment some counter. This doesn't seem like it would actually work out that well:
- wouldn't work with pytest's use of plain `assert` (probably, unless unittest's assertion methods are called under the hood).
- custom `TestCase`s with custom assert methods would now have to increment this new counter.
- Some assertions work by calling other assertion methods. This practice fails when an assertion methods calls other assertion methods. eg, [assertDictEqual](https://hg.python.org/cpython/file/tip/Lib/unittest/case.py#l1101). It would be very confusing to users to call `assertDictEqual` once, then have to increment the plan by two.

> Of those modes, tappy adopts the last one

And this makes sense. I believe node-tap adopts something like the first implementation. eg,

```js
import tap from 'tap';

tap.test('test a thing', function(t) {
    t.plan(2);
    t.ok('yep');

    t.test('this is a subtest', function(s) {
        s.ok('yyeepp');
    };
});
```
is equivalent to
```js
import tap from 'tap';

t.plan(2);
t.ok('yep');
t.ok('yeepp');
```


The test structure is more there for readability (and some utility w/ setup teardown methods), but each ok/not ok assertion is its own line.

**Comment by jchampio** [comment]
> Since tappy reports at the test method level and runners will run all tests, the plan should always match the count. If there is a mismatch, it would indicate a broken runner and not a broken test suite. [...] If test runners guarantee to run all tests even if there's an error, what would an explicit plan buy a developer?

If they're running tappy's output through a higher-level parser, a plan at the top (option 1) would help them quickly identify malfunctioning test runners. This isn't incredibly useful with small, self-contained test suites, but if a huge number of TAP-based suites are being aggregated into a single stream, I could see it being very useful. (I've worked on such an aggregator in the past.) Having a false positive because something `SIGKILL`'d tappy in the middle of a four-hour test run wouldn't be very fun.

For the record, though, if such an option were added to tappy, I'd like for it to be as hands-off as possible. Manually updating an explicit plan count wouldn't be very friendly; other TAP producers I've used have collected and counted the tests automatically before they're run.

**Comment by mblayman** [comment]
That sounds like it could be useful. Unfortunately, support for multiple plans in a single stream is not part of the spec. I even proposed such support last year for the next version of the spec and it was shown to be backwards incompatible (https://github.com/TestAnything/testanything.github.io/pull/36#discussion_r47317814)

Given that TAP won't be supporting single stream parsers, I don't think I have much personal interest in moving the plan to the top of the report. I suspect it would require some introspection magic across the various frameworks that would differ in method per framework. I'll opt for KISS here unless someone proposes an amazing PR that proves me wrong. :grinning:

**Comment by jchampio** [comment]
> Unfortunately, support for multiple plans in a single stream is not part of the spec. I even proposed such support last year for the next version of the spec and it was shown to be backwards incompatible

Right, but that's for the aggregator/multiplexer to deal with, not tappy. By moving the plan to the top, tappy simply makes it possible for aggregators to catch those problems in large systems. It makes the entire system more robust.

(I share your desire for subplans in TAP, by the way; that would remove the need for multiplexers entirely.)

> I suspect it would require some introspection magic across the various frameworks that would differ in method per framework. I'll opt for KISS here unless someone proposes an amazing PR that proves me wrong.

That sounds fair to me. :smile:
